#pragma once

// This model's class is only declared when it was actually selected in YAML
// (-DSEGLCD_ENABLE_PCF85134_XYGAX_SEG_I2C, generated by display.py). ESPHome's
// external_components build compiles every source file in this directory
// regardless of which model a given YAML picked, so this guard isn't about
// runtime dispatch (there is none anymore) - it just keeps this translation
// unit empty for builds that never reference this class, matching the vendor
// library header's own SEGLCD_DISABLE_ALL_LCDS/SEGLCD_ENABLE_* guard.
#ifdef SEGLCD_ENABLE_PCF85134_XYGAX_SEG_I2C

#include "seglcd.h"

#include "SegLCD_PCF85134_XygaxSegI2C.h"

namespace esphome {
namespace seglcd {

class SegLCDDisplayPcf85134XygaxSegI2c : public PollingComponent {
 public:
  SegLCDDisplayPcf85134XygaxSegI2c(uint8_t address, uint8_t subaddress)
      : lcd_(transport_, address, subaddress), address_(address), subaddress_(subaddress) {}

  void set_model_name(const char *model_name) { this->model_name_ = model_name; }
  void set_i2c_bus(i2c::I2CBus *bus) { this->transport_.set_i2c_bus(bus); }
  void set_writer(std::function<void(SegLCD_PCF85134_XygaxSegI2C &)> &&writer) {
    this->writer_ = std::move(writer);
    this->writer_configured_ = true;
  }

  void setup() override {
    if (seglcd_setup(this, this->transport_, this->lcd_))
      this->update();
  }

  void update() override {
    this->lcd_.clear();
    if (this->writer_configured_)
      this->writer_(this->lcd_);
    seglcd_update(this->lcd_);
  }

  void dump_config() override { seglcd_dump_config(this->model_name_, this->address_, this->subaddress_, this); }

  float get_setup_priority() const override { return setup_priority::DATA; }

 protected:
  // transport_ must be declared (and thus constructed) before lcd_: members
  // are constructed in declaration order, and SegLCD_PCF85134_XygaxSegI2C's
  // constructor takes transport_ by reference, so it must already be alive.
  SegLCDI2CTransport transport_;
  SegLCD_PCF85134_XygaxSegI2C lcd_;

  const char *model_name_{"unknown"};
  uint8_t address_;
  uint8_t subaddress_;
  std::function<void(SegLCD_PCF85134_XygaxSegI2C &)> writer_;
  bool writer_configured_{false};
};

}  // namespace seglcd
}  // namespace esphome

#endif  // SEGLCD_ENABLE_PCF85134_XYGAX_SEG_I2C
